feat(app); [WEB-4] created Navbar conponent & Dropdown conponent
VeeShort/website-react pull request #2
Opened 2020-12-12 00:10 UTC by EduardKurbatov

Was created navbar component and dropdown conponent.bouth components are adaptive for every screen resolution

2020-12-14 16:22 UTC, VeeShort requested changes
Few comments, also change every double-quote to single-quote in imports

2020-12-14 16:22 UTC, VeeShort commented on src/components/NavBar/NavBar.js
> +  const handleClick = () => setClick(!click);
It's better to rename `handleClick` to `toggleMobileMenu` for more code readability

2020-12-14 16:22 UTC, VeeShort commented on src/components/NavBar/NavBar.js
> +  const [click, setClick] = useState(false);
Please rename `click`and `setClick` to `isMenuActive` and `setMenuState` respectively

2020-12-14 16:22 UTC, VeeShort commented on src/components/NavBar/NavBar.js
> +  const [dropdown, setDropdown] = useState(false);
This one should be renamed to `isDropdownActive` and `setDropdownVisibility` respectively

2020-12-14 16:22 UTC, VeeShort commented on src/components/NavBar/NavBar.scss
> +        color: #999;
For not hardcoding and copy-pasting this color you can create a variable in `variables.scss` and just import it in every needed location

2020-12-14 16:22 UTC, VeeShort commented on src/components/NavBar/recovery
> +export default Dropdown;
Holy shit dude, what is that? Remove it before the Universe collapses

2020-12-14 16:25 UTC, VeeShort commented
PR title should be `feat(app): Navbar and Dropdown components`

2020-12-14 16:26 UTC, VeeShort requested changes
PR title should be `feat(app): [WEB-4] Navbar and Dropdown components`
Check spelling in the description

2020-12-14 18:26 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +    console.log(closeSub);
Remove console.log

2020-12-14 18:37 UTC, VeeShort requested changes

2020-12-14 18:37 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +    console.log(closeSub);
remove console.log

2020-12-14 18:37 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +    console.log(closeSubSub);
remove console.log

2020-12-14 18:38 UTC, VeeShort commented
@EduardKurbatov before you fix merge conflicts, run `npm i`

2020-12-15 22:46 UTC, EduardKurbatov commented on src/components/NavBar/Dropdown.scss
> +}
i need other solution here.Cuz sub-menu items are child elements for the first sub-menu item.If I try to do like on your example all child sub-menu items will be showed at the same time

2020-12-15 23:28 UTC, EduardKurbatov commented on src/components/NavBar/NavBar.js
> +  };
It's not true.Cuz if i clear the "else" part first sum-menu item will never hide

2020-12-16 00:07 UTC, EduardKurbatov commented on src/components/NavBar/recovery
> +export default Dropdown;
lol.I'm so sorry about that)

2020-12-16 12:50 UTC, VeeShort commented on src/components/NavBar/Dropdown.scss
> +}
@EduardKurbatov I see, then we can try this solution:
```css
#active-link_1:hover,
#active-link_2:hover {
  & > .sub-menu { visibility: visible; }
}
```

2020-12-16 15:19 UTC, VeeShort requested changes

2020-12-16 16:35 UTC, VeeShort requested changes
New chunk of comments

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +  };
I think we can change this logic to this:
```js
const [list, setList] = useState([false, false, false]);

const  clickHandler = (index) => {
  list[index] = !list[index];
  setList(list);
}
```
and then change `onClick`  in `render()`: 
```jsx
// ...
<span onClick={() => clickHandler(0)}>
// ...
<span onClick={() => clickHandler(1)}>
// and so on
```
and className check for the same `<span>` (this change will require to change hide/show logic in css):
```jsx
className={list[0] && 'active'}
```

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/NavBar.scss
> +$font-color: #999;
The same variable is already used in `Dropdown.scss`, create a separate file called `variables.scss` and put every variable there, then you can just  __@include__ it in places you need

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/NavBar.scss
> +      display: flex;
`.nav-menu` already has this property defined

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/NavBar.scss
> +    }
Move this css to `.nav-menu` and mention it like:
```scss
&.active {
  ...
}
```
Also remove next properties for `.active`:
`left, top` as they are already defined in `.nav-menu` and does not change for `.active`

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/NavBar.scss
> +    .navbar .nav-menu .nav-item.mobileNav {
Rename `mobileNav` to `nav-mobile`, lets be consistent with naming

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/Dropdown.scss
> +}
I think we can optimize this even better:
```scss
.active-link:hover {
  & > .sub-menu {
      visibility: visible;
  }
}
```
Don't forget to remove id's from the html

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +          <li className="active-link" id="second-link">
Remove this id. See a comment below in `Dropdown.scss`

2020-12-16 16:35 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +      <li className="active-link" id="first-link">
Remove this id. See a comment below in `Dropdown.scss`

2020-12-16 16:42 UTC, VeeShort commented on src/components/NavBar/Dropdown.js
> +  };
Further optimization possible

2020-12-16 17:50 UTC, VeeShort requested changes

2020-12-16 17:50 UTC, VeeShort commented on src/components/NavBar/NavBar.js
> +            <li className="nav-item" onisMenuActive={closeMobileMenu}>
What is `onisMenuActive`?

2020-12-16 19:20 UTC, VeeShort commented
Remove all imports for `React`

2020-12-23 01:33 UTC, EduardKurbatov commented on src/components/NavBar/Dropdown.js
> +  };
I try to do like on Your example and I got an error about infinite loop

2020-12-29 15:59 UTC, merged